### ISSUE TITLE
Implement rounding in the formatters

### ISSUE THREAD

**Issue by bojanz** [commerceguys/intl#18]
Every single number formatter out there (intl, number_format, Java's DecimalFormatter, the Ruby on Rails helper) also rounds. I've always found it bizarre (showing a value should not modify it), but silently truncating (like we do now) isn't ideal either.

The generally expected rounding modes are: ceiling, floor, up, down, half up, half down, half even (default in intl/icu), half odd. We can support the last four with round(). The first two will be tricky because ceil() and floor() have floating point bugs (which round() doesn't). Rounding down is truncating. Rounding up would need special code. 

Maybe we can get away with supporting only the round() ones?

**Comment by sustmi** [comment]
If you use floating point arithmetic rounding is desirable.
See the following test case:
```
$x = 10000 - (10000 - 0.58);
var_dump($x); // float(0.57999999999993)

$numberFormatter = new NumberFormatter($numberFormat, NumberFormatter::DECIMAL);
$numberFormatter->setMinimumFractionDigits(2);
$numberFormatter->setMaximumFractionDigits(10);
var_dump($numberFormatter->format($x)); // string(16) "0,5799999999 ¤"
```
I expected the result to be `0,58` rather than `0,5799999999`.

I think that NumberFormatter should provide configuration enabling rounding instead of truncating.

**Comment by bojanz** [comment]
Right. The library was built for an ecommerce use case, where the assumption is that you'd never use floating point arithmetic (opting for bcmath / gmp instead).

There's no doubt we should add some form of rounding, someone just needs to code it :)

**Comment by bojanz** [comment]
We have full rounding logic nowadays: https://github.com/commerceguys/intl/blob/master/src/Calculator.php

We just need to plug it into the formatters.

**Comment by sustmi** [comment]
Great news! Thanks.
