### ISSUE TITLE
Hey guys this is kind of big, when using the Language Repository I get an unknown language when calling get('en'). 

### ISSUE THREAD

**Issue by bitlinguist** [commerceguys/intl#19]
-  when using the Language Repository I get an unknown language when calling get('en')
- also looping threw them there is no English whatsoever

What is up with that?

**Comment by bojanz** [comment]
Looks like the dataset in the last release (v0.6) has a bug.
Try with master instead, confirm all is well, and I'll tag a v0.7

**Comment by bitlinguist** [comment]
The part of that message, 'Confirm all is well', do you mean test all in Language only or the all repo's?

Reason I am asking might be clarified by this, will v0.7.0 only have an up to date Language repo?

**Comment by bojanz** [comment]
Confirm that your bug is gone. All parts of the dataset have been updated, not just languages.

**Comment by bitlinguist** [comment]
Thanks I just wanted to confirm that I was not going to break stuff on your site

**Comment by bitlinguist** [comment]
You can go ahead making v0.7.0 from master I got the language by doing the following.
```php
$repo = new LanguageRepository()
var_dump($repo->get('en'));
```
object(CommerceGuys\Intl\Language\Language)[611]
  protected 'languageCode' => string 'en' (length=2)
  protected 'name' => string 'English' (length=7)
  protected 'locale' => string 'en' (length=2)

```json
{
    ...
    "require": {
        "commerceguys/intl": "dev-master"
    }
   ...
```

**Comment by bojanz** [comment]
Thanks. Tagged v0.6.1 (it made more sense than v0.7).

**Comment by bitlinguist** [comment]
Thanks! I agree. Was also confused on why you'd make a major looking release :).
