### ISSUE TITLE
Can you please add Latin-American Spanish (es-419)

### ISSUE THREAD

**Issue by jeroenpraat** [commerceguys/intl#26]
Yes I know it's not an official language code yet, but it is already used in Chrome/Chromium.

**Comment by bojanz** [comment]
We have all of the locales that inherit from it, like es-AR, es-BO, es-CL, etc. Is there a reason why you need the parent locale?

**Comment by jeroenpraat** [comment]
We are going to make a Latin American Spanish translation for our project (Hubzilla). Maybe later we also are going to make Mexican Spanish, Argentine Spanish, etc. translations.

**Comment by bojanz** [comment]
Okay, fair. We can remove es-419 from the "excluded" list in the generation scripts, but we also need to implement more complex inheritance rules, so that es-AR falls back to es-419, etc.

**Comment by jeroenpraat** [comment]
The latter one would be great, cause we now have symlinks (e.g. es-AR > es-419). Cause of that all those Spanish language locales make our language selector list overcrowded.

**Comment by bojanz** [comment]
Fixed in #45. Sorry for the long wait!
