### ISSUE TITLE
Country codes: ISO 3166-1 alpha-3

### ISSUE THREAD

**Issue by vercotux** [commerceguys/intl#28]
Is there any way to get country codes in 3-character format ([ISO 3166-1 alpha-3](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3))?

**Comment by bojanz** [comment]
See https://github.com/commerceguys/intl/blob/master/src/Country/CountryInterface.php#L34

**Comment by vercotux** [comment]
Per object that's fine, but what about when I need a list? getList in CountryRepository always seems to return a 2-character code. Any way to set the format?

**Comment by bojanz** [comment]
Iterate through the list, load the full object by country code, then get the 3-character codes.
The data is loaded already anyway, you are incurring no additional cost.

The 3-character and numeric codes are considered peripheral, which is why getList() doesn't return them.

**Comment by vercotux** [comment]
It would be cool if there was a simple way to set whether getList returns the keys in 3 or 2 char format.

But this solution will do for now. Thanks a lot!

**Comment by bojanz** [comment]
Fair point, I'll keep that in mind.
