### ISSUE TITLE
In Czech we use Kč not CZK

### ISSUE THREAD

**Issue by matak** [commerceguys/intl#31]
I mean the currency you call CZK but everywhere you use 

1 654,03 Kč
   654,03 Kč
     54,03 Kč

etc.

**Comment by bojanz** [comment]
Thanks. Please open a bug reports in the CLDR trac: http://unicode.org/cldr/trac/
And link it here so I can follow along. 
Once CLDR makes the change, it will be pulled in here automatically.

**Comment by matak** [comment]
Submission rejected as potential spam

Trac thinks your submission might be Spam. To prove otherwise please provide a response to the following.


sorry i tried, but i am not abble to create ticket

**Comment by bojanz** [comment]
You'll have to contact them and see why then (or try again later).

Out of the last two bug reports for CLDR data, one was addressed in CLDR v29 (and pulled into the library today), the other is scheduled for CLDR v30, so they've been very responsive.

**Comment by matak** [comment]
[http://unicode.org/cldr/trac/ticket/9360](url)

**Comment by bojanz** [comment]
Thanks!

**Comment by bojanz** [comment]
We've just pulled in CLDR v30, and this issue is now fixed.
