### ISSUE TITLE
Currency codes for CN, VG and ZA are incorrect

### ISSUE THREAD

**Issue by kitbs** [commerceguys/intl#35]
Thanks for your great library!

The currency codes in [base.json](https://github.com/commerceguys/intl/blob/master/resources/country/base.json) for CN, VG and ZA are incorrect due to the array ordering of the CLDR data. (See [currencyData.json#L979](https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/currencyData.json#L979), [#L3221](https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/currencyData.json#L3221), and [#L3348](https://github.com/unicode-cldr/cldr-core/blob/master/supplemental/currencyData.json#L3348).) CN has CNX instead of CNY, VG has GBP instead of USD and ZA has ZAL instead of ZAR. These are all historic or non-tender currencies.

In most countries in the list, the current currency is the last in the array, and in [generate.php#L78](https://github.com/commerceguys/intl/blob/master/scripts/country/generate.php#L78) you are using `key(end($currencyData['region'][$countryCode]))` to retrieve it. These three countries are differently sorted for some reason, and the current currency is not the last in the array.

Rather than rely on the sorting, which could be arbitrary (although it only has these 3 exceptions at the moment), could you use the `_from`, `_to` and `_tender` values to filter the currency array before returning the last key?

Here is a messy example that I made quickly to identify what was wrong with these three countries:

````php
// Determine the current currency for this country.
if (isset($currencyData['region'][$countryCode])) {

    $currencyCandidates = $currencyData['region'][$countryCode];
    $currencyCandidates = array_filter($currencyData['region'][$countryCode], function($currency) {

        $currency = end($currency);

        if (!isset($currency['_tender']) || $currency['_tender'] !== 'false') {
            $active = isset($currency['_to']) ? new DateTime <= new DateTime($currency['_to']) : true;
            $active = $active && (isset($currency['_from']) ? new DateTime >= new DateTime($currency['_from']) : true);

            return $active;
        }

    });

    if (!empty($currencyCandidates)) {
        $currentCurrency = key(end($currencyCandidates));
    }
    else {
        $currentCurrency = null;
    }

    $baseData[$countryCode]['currency_code'] = $currentCurrency;
}
````

**Comment by bojanz** [comment]
Makes sense, thanks.

**Comment by bojanz** [comment]
Updated CLDR to v30, this issue can now proceed.
