### ISSUE TITLE
How can I stop number translation in Drupal 8 

### ISSUE THREAD

**Issue by wisamx** [commerceguys/intl#69]
I am using Drupal 8 Commerce 2
My website is provided into English and Arabic
commerceguys/intl is used to localize numbers so in Arabic it uses NUMBERING_SYSTEM_ARABIC conversioin.
How can I stop this translation. and use English numbers for all languages.

The only way I am thinking about now is replace the letters manually in the intl library.

https://drupal.stackexchange.com/q/264335/86458

**Comment by bojanz** [comment]
You're asking a Drupal specific question in the library issue queue. Since any solution would be Drupal specific, there is nothing to answer on this side.
