### ISSUE TITLE
Language selection with uppercase not working

### ISSUE THREAD

**Issue by KevinXL** [commerceguys/intl#70]
Some off the language codes in the source file contains uppercase characters.
Because the strtolower it can't find the definition in:
https://github.com/commerceguys/intl/blob/22156e447530d6ebd387bfee51ef1ae2c70a5ff0/src/Language/LanguageRepository.php#L98

```
$languageRepository = new LanguageRepository();
$languageRepository->get('nl-BE');
```

**Comment by bojanz** [comment]
Thanks for the report!
