### ISSUE TITLE
Maximum and minimum fraction digits are always set in defaultOptions

### ISSUE THREAD

**Issue by artemvd** [commerceguys/intl#76]
This line of code https://github.com/commerceguys/intl/blob/0fc176165f45d9f3dd9af50a05293c3fa99e4691/src/Formatter/CurrencyFormatter.php#L105 and also https://github.com/commerceguys/intl/blob/0fc176165f45d9f3dd9af50a05293c3fa99e4691/src/Formatter/CurrencyFormatter.php#L108 makes no sense because in defaultOptions those array items are already set, so if your options array doesn't contain the minimum_fraction_digits or/and maximum_fraction_digits they will never be taken from the Currency config with the method getFractionDigits().

This causes the problems like this:

1. Currency is EUR
2. Currency fractionDigits is 2 (set in yml file, talking here about Drupal 8 implementation).
3. In price formatter no minimum or maximum fraction digits is set, so the format method in CurrencyFormatter uses the defaultOptions instead, they have as values: `null`, but still isset() returns true in lines 105 and 108.
4. Formatted price with number 5.123123 is shown like 5.123123 instead of 5.12 .

Proposed solution:
- replace !isset($options['minimum_fraction_digits'])) to empty($options['minimum_fraction_digits']))
- replace !isset($options['maximum_fraction_digits'])) to empty($options['maximum_fraction_digits']))

This way `null` value will force the method to get the settings from the Currency itself.

Pull request link: https://github.com/commerceguys/intl/pull/77

**Comment by bojanz** [comment]
I don't follow

isset() will return FALSE when given a NULL value. So the behavior you're requesting should already be there.

**Comment by artemvd** [comment]
Sorry, that was a mistake on my side, closing.
