### ISSUE TITLE
Reduce the number of available locales

### ISSUE THREAD

**Issue by bojanz** [commerceguys/intl#79]
I've done an analysis of the available locales, and concluded that easily half of them are non-essential and unlikely to be used. CLDR includes 75 African locales which represent non-official languages. It also includes minor European locales such as Walser and Western Frisian.

Each locale has a cost, in maintainer time when updating the dataset and verifying the results, and in memory costs (since NumberFormatRepository inlines all data, and each repository has its list of available locales). Plus the general weight of the library and number of files it contains. Furthermore, many of the smaller locales have partially translated data, with some missing translations completely.

So, I suggest imposing this ignore list (first 4 lines are already present):
```
$ignoredLocales = [
    // Esperanto, Interlingua, Volapuk are made up languages.
    'eo', 'ia', 'vo',
    // Church Slavic, Manx, Prussian are historical languages.
    'cu', 'gv', 'prg',
    // Africa secondary languages.
    'agq', 'ak', 'am', 'asa', 'bas', 'bem', 'bez', 'bm', 'cgg', 'dav',
    'dje', 'dua', 'dyo', 'ebu', 'ee', 'ewo', 'ff', 'ff-Latn', 'guz',
    'ha', 'ig', 'jgo', 'jmc', 'kab', 'kam', 'kea', 'kde', 'ki', 'kkj',
    'kln', 'khq', 'ksb', 'ksf', 'lag', 'luo', 'luy', 'lu', 'lg', 'ln',
    'mas', 'mer', 'mua', 'mgo', 'mgh', 'mfe', 'naq', 'nd', 'nmg', 'nnh',
    'nus', 'nyn', 'om', 'rof', 'rwk', 'saq', 'seh', 'ses', 'sbp', 'sg',
    'shi', 'sn', 'teo', 'ti', 'tzm', 'twq', 'vai', 'vai-Latn', 'vun',
    'wo', 'xog', 'xh', 'zgh', 'yav', 'yo', 'zu',
    // Europe secondary languages.
    'br', 'dsb', 'fo', 'fur', 'fy', 'hsb', 'ksh', 'kw', 'nds', 'or', 'rm',
    'se', 'smn', 'wae',
    // Other infrequently used locales.
    'ceb', 'ccp', 'chr', 'ckb', 'haw', 'ii', 'jv', 'kl', 'kn', 'lkt',
    'lrc', 'mi', 'mzn', 'os', 'qu', 'row', 'sah', 'tt', 'ug', 'yi',
];
```
This creates a danger of accidentally dropping a locale that people rely on, but it would be easy enough to revert such a change.

**Comment by deakjahn** [comment]
@bojanz Esperanto is artificial but is used actively in the world and on the net. Your decision made it impossible to set up a webshop with proper support for addresses and other needs of localization. Such treatment of historical and similar languages are understandable but currently used ones, no matter whether organic or artificial, are not.
