### ISSUE TITLE
Name changes

### ISSUE THREAD

**Issue by mc-chris-zeigler** [commerceguys/intl#87]
Hey! Love the work you guys have done! I wanted to provide a couple mentions/updates as I work on internationalization for my team:

- The code for Kosovo changed from KV to XK. 
- Swaziland is now called Eswatini: https://en.wikipedia.org/wiki/Eswatini

Thanks guys!

**Comment by bojanz** [comment]
Hi, this package only packages data from https://cldr.unicode.org/, we don't edit the data on our own.

Kosovo has always been under XK, as it hasn't been assigned an ISO code at all.
Looks like CLDR is tracking the Swaziland rename: https://unicode-org.atlassian.net/browse/CLDR-11063 so it will probably land in CLDR v42.
